### ISSUE TITLE
Error adapter when on socks proxy

### ISSUE THREAD

**Issue by instalator** [ioBroker/ioBroker.telegram#59] opened 2018-06-06 15:57 UTC
Caught | 2018-06-06 22:49:29.815 | error | by controller[3]: at TCP.onread (net.js:547:20)
Caught | 2018-06-06 22:49:29.814 | error | by controller[3]: at readableAddChunk (_stream_readable.js:176:18)
Caught | 2018-06-06 22:49:29.813 | error | by controller[3]: at Socket.emit (events.js:188:7)
Caught | 2018-06-06 22:49:29.813 | error | by controller[3]: at emitOne (events.js:96:13)
Caught | 2018-06-06 22:49:29.812 | error | by controller[3]: at Socket.Parser.__onData (C:\ioBroker\node_modules\iobroker.telegram\node_modules\socksv5\lib\client.parser.js:33:10)
Caught | 2018-06-06 22:49:29.810 | error | by controller[3]: at Parser._onData (C:\ioBroker\node_modules\iobroker.telegram\node_modules\socksv5\lib\client.parser.js:122:21)
Caught | 2018-06-06 22:49:29.809 | error | by controller[3]: 2018-06-06 22:49:29.240 - telegram.0 Error: ttl expired
Caught | 2018-06-06 22:49:29.808 | error | by controller[2]: 2018-06-06 22:49:29.238 - telegram.0 uncaught exception: ttl expired
Caught | 2018-06-06 22:49:29.807 | error | by controller[1]: at TCP.onread (net.js:547:20) code: 'ETTLEXPIRED' }
Caught | 2018-06-06 22:49:29.806 | error | by controller[1]: at readableAddChunk (_stream_readable.js:176:18)
Caught | 2018-06-06 22:49:29.805 | error | by controller[1]: at Socket.emit (events.js:188:7)
Caught | 2018-06-06 22:49:29.804 | error | by controller[1]: at emitOne (events.js:96:13)
Caught | 2018-06-06 22:49:29.803 | error | by controller[1]: at Socket.Parser.__onData (C:\ioBroker\node_modules\iobroker.telegram\node_modules\socksv5\lib\client.parser.js:33:10)
Caught | 2018-06-06 22:49:29.801 | error | by controller[1]: at Parser._onData (C:\ioBroker\node_modules\iobroker.telegram\node_modules\socksv5\lib\client.parser.js:122:21)
Caught | 2018-06-06 22:49:29.799 | error | by controller[1]: { Error: ttl expired

**Comment by BuZZy1337** [comment] 2018-07-29 23:45
The Error says ttl expired.. Maybe there was a problem with the proxy server? Or is this happening every time?

**Comment by BuZZy1337** [comment] 2018-07-30 18:07
Okay, I'm closing this issue - Because I think it is not caused by the adapter. :+1:

**Closed by BuZZy1337** 2018-07-30 18:07 UTC
Labels: question
