### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by instalator** [ioBroker/ioBroker.telegram#58] opened 2018-06-06 15:56 UTC
Caught | 2018-06-06 22:50:01.241 | error | by controller[0]: See https://github.com/yagop/node-telegram-bot-api/issues/319. at module.js:570:32
Caught | 2018-06-06 22:50:01.240 | error | by controller[0]: In the future, you will have to enable it yourself.
Caught | 2018-06-06 22:50:01.238 | error | by controller[0]: Wed, 06 Jun 2018 15:49:35 GMT node-telegram-bot-api deprecated Automatic enabling of cancellation of promises is deprecated.

**Comment by BuZZy1337** [comment] 2018-06-06 16:14
Duplicate of #57

**Closed by BuZZy1337** 2018-06-06 16:14 UTC
